public class tempuriOrgCredifeye {
  /*  public class validateEmail_element {
        public String emailid;
        private String[] emailid_type_info = new String[]{'emailid','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{'emailid'};
    }
    public class UserRegistrationProjectCentral_element {
        public String FirstName;
        public String LastName;
        public String EmailAddress;
        public String Password;
        public String CompanyName;
        public String CompanyUrl;
        private String[] FirstName_type_info = new String[]{'FirstName','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] LastName_type_info = new String[]{'LastName','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] EmailAddress_type_info = new String[]{'EmailAddress','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] Password_type_info = new String[]{'Password','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] CompanyName_type_info = new String[]{'CompanyName','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] CompanyUrl_type_info = new String[]{'CompanyUrl','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{'FirstName','LastName','EmailAddress','Password','CompanyName','CompanyUrl'};
    }
    public class CampaignCreistmas_element {
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class NewsRegistrationResponse_element {
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{};
    }
    public class validateEmailResponse_element {
        public String validateEmailResult;
        private String[] validateEmailResult_type_info = new String[]{'validateEmailResult','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{'validateEmailResult'};
    }
    public class UpdateOutLookInfo_element {
        public String UserEmailId;
        public String C_FullName;
        public String C_EmailId;
        public String C_MobileNo;
        public String C_BusinessPhNo;
        public String C_HomePhNo;
        public String C_BusinessFaxNo;
        public String C_Businessaddr;
        public String C_HomeAddr;
        public String C_Company;
        public String C_Title;
        public String C_EmailId1;
        public String C_EmailId2;
        private String[] UserEmailId_type_info = new String[]{'UserEmailId','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_FullName_type_info = new String[]{'C_FullName','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_EmailId_type_info = new String[]{'C_EmailId','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_MobileNo_type_info = new String[]{'C_MobileNo','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_BusinessPhNo_type_info = new String[]{'C_BusinessPhNo','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_HomePhNo_type_info = new String[]{'C_HomePhNo','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_BusinessFaxNo_type_info = new String[]{'C_BusinessFaxNo','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_Businessaddr_type_info = new String[]{'C_Businessaddr','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_HomeAddr_type_info = new String[]{'C_HomeAddr','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_Company_type_info = new String[]{'C_Company','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_Title_type_info = new String[]{'C_Title','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_EmailId1_type_info = new String[]{'C_EmailId1','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] C_EmailId2_type_info = new String[]{'C_EmailId2','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{'UserEmailId','C_FullName','C_EmailId','C_MobileNo','C_BusinessPhNo','C_HomePhNo','C_BusinessFaxNo','C_Businessaddr','C_HomeAddr','C_Company','C_Title','C_EmailId1','C_EmailId2'};
    }
    public class UpdateOutLookInfoResponse_element {
        public Boolean UpdateOutLookInfoResult;
        private String[] UpdateOutLookInfoResult_type_info = new String[]{'UpdateOutLookInfoResult','http://www.w3.org/2001/XMLSchema','boolean','1','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{'UpdateOutLookInfoResult'};
    }
    
    public class WebServiceSoap {
    	
        public String endpoint_x = 'http://119.82.98.194/icpv4/CampaignCreistmas.asmx';
        public Map<String,String> inputHttpHeaders_x;
        public Map<String,String> outputHttpHeaders_x;
        public String clientCertName_x;
        public String clientCert_x;
        public String clientCertPasswd_x;
        public Integer timeout_x;
        private String[] ns_map_type_info = new String[]{'http://tempuri.org/', 'tempuriOrgCredifeye'};
        /*public String CampaignCreistmas() {
            tempuriOrgCredifeye.CampaignCreistmas_element request_x = new tempuriOrgCredifeye.CampaignCreistmas_element();
            tempuriOrgCredifeye.CampaignCreistmasResponse_element response_x;
            Map<String, tempuriOrgCredifeye.CampaignCreistmasResponse_element> response_map_x = new Map<String, tempuriOrgCredifeye.CampaignCreistmasResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://tempuri.org/CampaignCreistmas',
              'http://tempuri.org/',
              'CampaignCreistmas',
              'http://tempuri.org/',
              'CampaignCreistmasResponse',
              'tempuriOrgCredifeye.CampaignCreistmasResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.CampaignCreistmasResult;
        }
        public String Registration(String FirstName,String phone,String Email) {
            tempuriOrgCredifeye.Registration_element request_x = new tempuriOrgCredifeye.Registration_element();
            tempuriOrgCredifeye.RegistrationResponse_element response_x;
            request_x.FirstName = FirstName;
            request_x.phone = phone;
            request_x.Email = Email;
            Map<String, tempuriOrgCredifeye.RegistrationResponse_element> response_map_x = new Map<String, tempuriOrgCredifeye.RegistrationResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://tempuri.org/Registration',
              'http://tempuri.org/',
              'Registration',
              'http://tempuri.org/',
              'RegistrationResponse',
              'tempuriOrgCredifeye.RegistrationResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.RegistrationResult;
        }
        */
       /* public String validateEmail(String emailid) {
            tempuriOrgCredifeye.validateEmail_element request_x = new tempuriOrgCredifeye.validateEmail_element();
            tempuriOrgCredifeye.validateEmailResponse_element response_x;
            request_x.emailid = emailid;
            Map<String, tempuriOrgCredifeye.validateEmailResponse_element> response_map_x = new Map<String, tempuriOrgCredifeye.validateEmailResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://tempuri.org/validateEmail',
              'http://tempuri.org/',
              'validateEmail',
              'http://tempuri.org/',
              'validateEmailResponse',
              'tempuriOrgCredifeye.validateEmailResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.validateEmailResult;
        }.....*/
     /*   public void NewsRegistration(String mailid) {
            tempuriOrgCredifeye.NewsRegistration_element request_x = new tempuriOrgCredifeye.NewsRegistration_element();
            tempuriOrgCredifeye.NewsRegistrationResponse_element response_x;
            request_x.mailid = mailid;
            Map<String, tempuriOrgCredifeye.NewsRegistrationResponse_element> response_map_x = new Map<String, tempuriOrgCredifeye.NewsRegistrationResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://tempuri.org/NewsRegistration',
              'http://tempuri.org/',
              'NewsRegistration',
              'http://tempuri.org/',
              'NewsRegistrationResponse',
              'tempuriOrgCredifeye.NewsRegistrationResponse_element'}
            );
            response_x = response_map_x.get('response_x');
        }
        public Boolean UpdateOutLookInfo(String UserEmailId,String C_FullName,String C_EmailId,String C_MobileNo,String C_BusinessPhNo,String C_HomePhNo,String C_BusinessFaxNo,String C_Businessaddr,String C_HomeAddr,String C_Company,String C_Title,String C_EmailId1,String C_EmailId2) {
            tempuriOrgCredifeye.UpdateOutLookInfo_element request_x = new tempuriOrgCredifeye.UpdateOutLookInfo_element();
            tempuriOrgCredifeye.UpdateOutLookInfoResponse_element response_x;
            request_x.UserEmailId = UserEmailId;
            request_x.C_FullName = C_FullName;
            request_x.C_EmailId = C_EmailId;
            request_x.C_MobileNo = C_MobileNo;
            request_x.C_BusinessPhNo = C_BusinessPhNo;
            request_x.C_HomePhNo = C_HomePhNo;
            request_x.C_BusinessFaxNo = C_BusinessFaxNo;
            request_x.C_Businessaddr = C_Businessaddr;
            request_x.C_HomeAddr = C_HomeAddr;
            request_x.C_Company = C_Company;
            request_x.C_Title = C_Title;
            request_x.C_EmailId1 = C_EmailId1;
            request_x.C_EmailId2 = C_EmailId2;
            Map<String, tempuriOrgCredifeye.UpdateOutLookInfoResponse_element> response_map_x = new Map<String, tempuriOrgCredifeye.UpdateOutLookInfoResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://tempuri.org/UpdateOutLookInfo',
              'http://tempuri.org/',
              'UpdateOutLookInfo',
              'http://tempuri.org/',
              'UpdateOutLookInfoResponse',
              'tempuriOrgCredifeye.UpdateOutLookInfoResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.UpdateOutLookInfoResult;
        }
        public String UserRegistrationProjectCentral(String FirstName,String LastName,String EmailAddress,String Password,String CompanyName,String CompanyUrl) {
            tempuriOrgCredifeye.UserRegistrationProjectCentral_element request_x = new tempuriOrgCredifeye.UserRegistrationProjectCentral_element();
            tempuriOrgCredifeye.UserRegistrationProjectCentralResponse_element response_x;
            request_x.FirstName = FirstName;
            request_x.LastName = LastName;
            request_x.EmailAddress = EmailAddress;
            request_x.Password = Password;
            request_x.CompanyName = CompanyName;
            request_x.CompanyUrl = CompanyUrl;
            Map<String, tempuriOrgCredifeye.UserRegistrationProjectCentralResponse_element> response_map_x = new Map<String, tempuriOrgCredifeye.UserRegistrationProjectCentralResponse_element>();
            response_map_x.put('response_x', response_x);
            WebServiceCallout.invoke(
              this,
              request_x,
              response_map_x,
              new String[]{endpoint_x,
              'http://tempuri.org/UserRegistrationProjectCentral',
              'http://tempuri.org/',
              'UserRegistrationProjectCentral',
              'http://tempuri.org/',
              'UserRegistrationProjectCentralResponse',
              'tempuriOrgCredifeye.UserRegistrationProjectCentralResponse_element'}
            );
            response_x = response_map_x.get('response_x');
            return response_x.UserRegistrationProjectCentralResult;
        }*/
   /* }
    public class UserRegistrationProjectCentralResponse_element {
        public String UserRegistrationProjectCentralResult;
        private String[] UserRegistrationProjectCentralResult_type_info = new String[]{'UserRegistrationProjectCentralResult','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{'UserRegistrationProjectCentralResult'};
    }
    public class RegistrationResponse_element {
        public String RegistrationResult;
        private String[] RegistrationResult_type_info = new String[]{'RegistrationResult','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{'RegistrationResult'};
    }
    public class Registration_element {  
        public String FirstName;
        public String phone;
        public String Email;
        private String[] FirstName_type_info = new String[]{'FirstName','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] phone_type_info = new String[]{'phone','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] Email_type_info = new String[]{'Email','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{'FirstName','phone','Email'};
    }
    public class CampaignCreistmasResponse_element {
        public String CampaignCreistmasResult;
        private String[] CampaignCreistmasResult_type_info = new String[]{'CampaignCreistmasResult','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{'CampaignCreistmasResult'};
    }
    public class NewsRegistration_element {
        public String mailid;
        private String[] mailid_type_info = new String[]{'mailid','http://www.w3.org/2001/XMLSchema','string','0','1','false'};
        private String[] apex_schema_type_info = new String[]{'http://tempuri.org/','true','false'};
        private String[] field_order_type_info = new String[]{'mailid'};
    }
   public static testmethod void testTempuriOrgCredifeye(){
    	
      	
      	tempuriOrgCredifeye.NewsRegistration_element nr=new tempuriOrgCredifeye.NewsRegistration_element();
      	nr.mailid='samplecredifeye@test.com';
      	tempuriOrgCredifeye.CampaignCreistmasResponse_element ccre=new tempuriOrgCredifeye.CampaignCreistmasResponse_element(); 	
    	ccre.CampaignCreistmasResult='testdata'; 
    	tempuriOrgCredifeye.UserRegistrationProjectCentral_element URC= new tempuriOrgCredifeye.UserRegistrationProjectCentral_element();
    	URC.CompanyName='samplecompany';
    	URC.CompanyUrl='http://www.w3.org/2001/XMLSchema';
    	URC.EmailAddress='Sample@test.com';
    	URC.FirstName='John';
    	URC.LastName='stat';
    	URC.Password='password';
    	tempuriOrgCredifeye.validateEmailResponse_element VER= new tempuriOrgCredifeye.validateEmailResponse_element();
    	VER.validateEmailResult='valid emailid';
    	tempuriOrgCredifeye.UpdateOutLookInfo_element UOL=new tempuriOrgCredifeye.UpdateOutLookInfo_element();
    	UOL.C_Businessaddr='Wallstreet,Newyork';
    	UOL.C_BusinessFaxNo='8748374847';
    	UOL.C_BusinessPhNo='7489387467';
    	UOL.C_Company='sampleco.';
    	UOL.C_EmailId='sample@in.com';
    	UOL.C_EmailId1='sample1@in.com';
    	UOL.C_EmailId2='Sample2@in.com';
    	UOL.C_FullName='testsample';
    	UOL.C_HomeAddr='beverlyhills,CA';
    	UOL.C_HomePhNo='7839478763';
    	UOL.C_MobileNo='5645678987';
    	UOL.C_Title='test';
    	UOL.UserEmailId='sampletest@test.com';
    	UpdateOutLookInfoResponse_element UOLR=new UpdateOutLookInfoResponse_element();
    	UOLR.UpdateOutLookInfoResult=true;
    	UserRegistrationProjectCentralResponse_element URPC=new UserRegistrationProjectCentralResponse_element();
    	URPC.UserRegistrationProjectCentralResult='recieved';
    	RegistrationResponse_element RR=new RegistrationResponse_element();
    	RR.RegistrationResult='sampledata';
    	Registration_element RE=new Registration_element();
    	RE.Email='sample@test.com';
    	RE.FirstName='testdata';
    	RE.phone='9473874675'; 
    	
 
 		tempuriOrgCredifeye.WebServiceSoap tdc=new tempuriOrgCredifeye.WebServiceSoap();
		tdc.endpoint_x='http://119.82.98.194/icpv4/CampaignCreistmas.asmx';
        tdc.validateEmail('sample@in.com');
    }*/
   
}