@IsTest 

private class TestSalesLast3Montha{  /*  
static testmethod void testSalesLast3Montha() 
{
         SalesLast3Montha s2= new SalesLast3Montha();
 
  s2.getWinnerAssignConv();
  s2.getWinnerSelfGenConv();
  s2.getWinnerFollowups();
  s2.getWinnerSampleReq();
  s2.getWinnerSampleDeal();
  s2.getWinnerSampleConv();


s2.getIndiansAssignConv();
  s2.getIndiansselfGenConv();
  s2.getIndiansFollowups();
  s2.getIndianssampleReq();
  s2.getIndianssampleDeal();
  s2.getIndianssampleConv();



 s2.getMauryasAssignConv();
  s2.getMauryasselfGenConv();
  s2.getMauryasFollowups();
  s2.getMauryassampleReq();
  s2.getMauryassampleDeal();
  s2.getMauryassampleConv();



 s2.getTitansAssignConv();
  s2.getTitanselfGenConv();
  s2.getTitansFollowups();
  s2.getTitansampleReq();
  s2.getTitansampleDeal();
  s2.getTitansampleConv();


s2.getRainmakersAssignConv();
  s2.getRainmakerselfGenConv();
  s2.getRainmakersFollowups();
  s2.getRainmakersampleReq();
  s2.getRainmakersampleDeal();
  s2.getRainmakersampleConv();
 

}*/}