@IsTest 

private class TestSalesLastMonth1b{    /*
static testmethod void testSalesLastMonth1b() 
{
    SalesLastMonth1b s3= new SalesLastMonth1b();
     s3.getMavericksDeal();
  s3.getMavericksLeads();
  s3.getMavericksDealConv();
  s3.getMavericksAssignLeads();
  s3.getMavericksselfGenLeads();
 
  
  s3.getJaguarsDeal();
  s3.getJaguarsLeads();
  s3.getJaguarsDealConv();
  s3.getJaguarsAssignLeads();
  s3.getJaguarsselfGenLeads();
  
     
     
   s3.getSpartansDeal();
  s3.getSpartansLeads();
  s3.getSpartansDealConv();
  s3.getSpartansAssignLeads();
  s3.getSpartanselfGenLeads();
 
    
   s3.getGladiatorsDeal();
  s3.getGladiatorsLeads();
  s3.getGladiatorsDealConv();
  s3.getGladiatorsAssignLeads();
  s3.getGladiatorselfGenLeads();
  
  
   s3.getMillionairesDeal();
  s3.getMillionairesLeads();
  s3.getMillionairesDealConv();
  s3.getMillionairesAssignLeads();
  s3.getMillionaireselfGenLeads();
 
 
 
s3.getTotalsDeal();
  s3.getTotalsLeads();
  s3.getTotalsDealConv();
  s3.getTotalsAssignLeads();
  s3.getTotalselfGenLeads();

}*/}