@IsTest 

private class TestSalesLastMonth1c{ /*    
static testmethod void testSalesLastMonth1c() 
{
         SalesLastMonth1c s4= new SalesLastMonth1c(); 
  
  s4.getMavericksAssignConv();
  s4.getMavericksselfGenConv();
  s4.getMavericksFollowups();
  s4.getMaverickssampleReq();
  s4.getMaverickssampleDeal();
  s4.getMaverickssampleConv();


  s4.getJaguarsAssignConv();
  s4.getJaguarsselfGenConv();
  s4.getJaguarsFollowups();
  s4.getJaguarssampleReq();
  s4.getJaguarssampleDeal();
  s4.getJaguarssampleConv();



 s4.getSpartansAssignConv();
  s4.getSpartanselfGenConv();
  s4.getSpartansFollowups();
  s4.getSpartansampleReq();
  s4.getSpartansampleDeal();
  s4.getSpartansampleConv();



 s4.getGladiatorsAssignConv();
  s4.getGladiatorselfGenConv();
  s4.getGladiatorsFollowups();
  s4.getGladiatorsampleReq();
  s4.getGladiatorsampleDeal();
  s4.getGladiatorsampleConv();


s4.getMillionairesAssignConv();
  s4.getMillionaireselfGenConv();
  s4.getMillionairesFollowups();
  s4.getMillionairesampleReq();
  s4.getMillionairesampleDeal();
  s4.getMillionairesampleConv();
  
  
   s4.getTotalsAssignConv();
  s4.getTotalsFollowups();
  s4.getTotalsampleReq();
  s4.getTotalsampleDeal();
  s4.getTotalsampleConv();
 

}*/}