@Istest
private class TestSalesReport{ /*
  static testmethod void TestSalesReport(){
  
  SalesReport S1=new SalesReport();
  s1.getSalesItems();
  //functions of this month sales report
  s1.getfunTotalL();
  s1.getfunTotalD();
  s1.getfunDealConv();
  s1.getfunSelfDC();
  s1.getfunTotalSelfL();
  s1.getfunSelfDealConv();
  s1.getfunAssignedDealConv();
  s1.getfunSampleDealConv();
  s1.getfunAssLC();
  s1.getfunAssOC();
  s1.getfunAssDC();
  s1.getfunXfUpLead();
  s1.getfunTotalAssL();
  s1.getfunXfUpOpp();
  s1.getfunTotalFUp();
  s1.getfunTSR();
  s1.getfunSTD();
  s1.getfunSelfLC();
  s1.getfunSelfOC();
  //functions of last month sales report
  s1.getSalesItems1();
  s1.getfunTotalL1();
  s1.getfunTotalD1();
  s1.getfunDealConv1();
  s1.getfunSelfDC1();
  s1.getfunTotalSelfL1();
  s1.getfunSelfDealConv1();
  s1.getfunAssignedDealConv1();
  s1.getfunSampleDealConv1();
  s1.getfunAssLC1();
  s1.getfunAssOC1();
  s1.getfunAssDC1();
  s1.getfunXfUpLead1();
  s1.getfunTotalAssL1();
  s1.getfunXfUpOpp1();
  s1.getfunTotalFUp1();
  s1.getfunTSR1();
  s1.getfunSTD1();
  s1.getfunSelfLC1();
  s1.getfunSelfOC1();
  //functions of last 3 months sales report
  s1.getSalesItems2();
   s1.getfunTotalL2();
  s1.getfunTotalD2();
  s1.getfunDealConv2();
  s1.getfunSelfDC2();
  s1.getfunTotalSelfL2();
  s1.getfunSelfDealConv2();
  s1.getfunAssignedDealConv2();
  s1.getfunSampleDealConv2();
  s1.getfunAssLC2();
  s1.getfunAssOC2();
  s1.getfunAssDC2();
  s1.getfunXfUpLead2();
  s1.getfunTotalAssL2();
  s1.getfunXfUpOpp2();
  s1.getfunTotalFUp2();
  s1.getfunTSR2();
  s1.getfunSTD2();
  s1.getfunSelfLC2();
  s1.getfunSelfOC2();
  }
*/}