@IsTest 

private class TestSalesLast1Month{  
/*  
static testmethod void testSalesLast1Month() 
{
 
  SalesLastMonth1 s1= new SalesLastMonth1(); 
 
  s1.getWinnersDeal();
  s1.getWinnersLeads();
  s1.getWinnerDealConv();
  s1.getWinnerAssignLeads();
  s1.getWinnerSelfGenLeads();
 
  
  s1.getIndiansDeal();
  s1.getIndiansLeads();
  s1.getIndiansDealConv();
  s1.getIndiansAssignLeads();
  s1.getIndiansselfGenLeads();
  
     
     
   s1.getMauryasDeal();
  s1.getMauryasLeads();
  s1.getMauryasDealConv();
  s1.getMauryasAssignLeads();
  s1.getMauryasselfGenLeads();
 
    
   s1.getTitansDeal();
  s1.getTitansLeads();
  s1.getTitansDealConv();
  s1.getTitansAssignLeads();
  s1.getTitanselfGenLeads();
  
  
   s1.getRainmakersDeal();
  s1.getRainmakersLeads();
  s1.getRainmakersDealConv();
  s1.getRainmakersAssignLeads();
  s1.getRainmakerselfGenLeads();
 
 
 

  
 
   
} */
}